/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/stats/inactive_users": {
    post: operations["inactive_users_stats_inactive_users_post"];
  };
  "/stats/slow_explores": {
    post: operations["slow_explores_stats_slow_explores_post"];
  };
  "/stats/large_explores": {
    post: operations["large_explores_stats_large_explores_post"];
  };
  "/stats/unused_explores": {
    post: operations["unused_explores_stats_unused_explores_post"];
  };
  "/stats/abandoned_dashboards": {
    post: operations["abandoned_dashboards_stats_abandoned_dashboards_post"];
  };
  "/stats/overused_queries": {
    post: operations["overused_queries_stats_overused_queries_post"];
  };
  "/": {
    get: operations["health_check__get"];
  };
}

export interface components {
  schemas: {
    /** AbandonedDashboardResult */
    AbandonedDashboardResult: {
      /**
       * Name
       * @default Abandoned Dashboards
       * @enum {string}
       */
      name?: "Abandoned Dashboards";
      /**
       * Test Id
       * @default abandoned_dashboards
       * @enum {string}
       */
      test_id?: "abandoned_dashboards";
      /** Pct Abandoned */
      pct_abandoned: number;
      /** Count Abandoned */
      count_abandoned: number;
      /** Sample Abandoned Dashboards */
      sample_abandoned_dashboards: components["schemas"]["DashboardUsage"][];
      /**
       * Grade
       * @enum {string}
       */
      grade?: "bad" | "ok" | "good";
    };
    /** DashboardUsage */
    DashboardUsage: {
      /** Dashboard Id */
      dashboard_id: string;
      /** Dashboard Title */
      dashboard_title: string;
      /** Query Count */
      query_count: number;
    };
    /** ExplorePerformance */
    ExplorePerformance: {
      /** Query.Model */
      "query.model": string;
      /** Query.View */
      "query.view": string;
      /** History.Average Runtime */
      "history.average_runtime": number;
      /** History.Max Runtime */
      "history.max_runtime": number;
    };
    /** ExploreQueries */
    ExploreQueries: {
      /** Model */
      model: string;
      /** Explore */
      explore: string;
      /** Query Run Count */
      query_run_count: number;
    };
    /** ExploreSize */
    ExploreSize: {
      /** Model */
      model: string;
      /** Explore */
      explore: string;
      /** Field Count */
      field_count: number;
    };
    /** ExploreSizeResult */
    ExploreSizeResult: {
      /**
       * Name
       * @default Large Explores
       * @enum {string}
       */
      name?: "Large Explores";
      /**
       * Test Id
       * @default large_explores
       * @enum {string}
       */
      test_id?: "large_explores";
      /** Large Explores */
      large_explores: components["schemas"]["ExploreSize"][];
      /** Median Explore Size */
      median_explore_size: number;
      /**
       * Grade
       * @enum {string}
       */
      grade?: "bad" | "ok" | "good";
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InactiveUserResult */
    InactiveUserResult: {
      /**
       * Name
       * @default Inactive Users
       * @enum {string}
       */
      name?: "Inactive Users";
      /**
       * Test Id
       * @default inactive_users
       * @enum {string}
       */
      test_id?: "inactive_users";
      /** Pct Inactive */
      pct_inactive: number;
      /** Sample User Names */
      sample_user_names: string[];
      /**
       * Grade
       * @enum {string}
       */
      grade?: "bad" | "ok" | "good";
    };
    /** LookerConfig */
    LookerConfig: {
      /** Host Url */
      host_url: string;
      /** Port */
      port: number;
      /** Client Id */
      client_id: string;
      /** Client Secret */
      client_secret: string;
    };
    /** OverusedQueryResult */
    OverusedQueryResult: {
      /**
       * Name
       * @default Overused Queries
       * @enum {string}
       */
      name?: "Overused Queries";
      /**
       * Test Id
       * @default overused_queries
       * @enum {string}
       */
      test_id?: "overused_queries";
      /** Sample Overused Queries */
      sample_overused_queries: components["schemas"]["QueryUsage"][];
      /**
       * Grade
       * @enum {string}
       */
      grade?: "bad" | "ok" | "good";
    };
    /** QueryUsage */
    QueryUsage: {
      /** Query.View */
      "query.view": string;
      /** Query.Model */
      "query.model": string;
      /** Query.Id */
      "query.id": string;
      /** History.Issuer Source */
      "history.issuer_source": string;
      /** History.Source */
      "history.source": string;
      /** History.Database Result Query Count */
      "history.database_result_query_count": number;
    };
    /** SlowExploresResult */
    SlowExploresResult: {
      /**
       * Name
       * @default Slow Explores
       * @enum {string}
       */
      name?: "Slow Explores";
      /**
       * Test Id
       * @default slow_explores
       * @enum {string}
       */
      test_id?: "slow_explores";
      /** Slow Explores */
      slow_explores: components["schemas"]["ExplorePerformance"][];
      /**
       * Grade
       * @enum {string}
       */
      grade?: "bad" | "ok" | "good";
    };
    /** UnusedExploreResult */
    UnusedExploreResult: {
      /**
       * Name
       * @default Unused Explores
       * @enum {string}
       */
      name?: "Unused Explores";
      /**
       * Test Id
       * @default unused_explores
       * @enum {string}
       */
      test_id?: "unused_explores";
      /** Unused Explores */
      unused_explores: components["schemas"]["ExploreQueries"][];
      /** Unused Percentage */
      unused_percentage: number;
      /**
       * Grade
       * @enum {string}
       */
      grade?: "bad" | "ok" | "good";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  inactive_users_stats_inactive_users_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InactiveUserResult"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LookerConfig"];
      };
    };
  };
  slow_explores_stats_slow_explores_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SlowExploresResult"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LookerConfig"];
      };
    };
  };
  large_explores_stats_large_explores_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExploreSizeResult"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LookerConfig"];
      };
    };
  };
  unused_explores_stats_unused_explores_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UnusedExploreResult"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LookerConfig"];
      };
    };
  };
  abandoned_dashboards_stats_abandoned_dashboards_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AbandonedDashboardResult"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LookerConfig"];
      };
    };
  };
  overused_queries_stats_overused_queries_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OverusedQueryResult"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LookerConfig"];
      };
    };
  };
  health_check__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}

export interface external {}
